### Teste da API - Verificar se está online
GET http://localhost:4000/api/teste

###

### Buscar todos os produtos
GET http://localhost:4000/api/products

###

### Cadastrar um novo produto
POST http://localhost:4000/api/products
Content-Type: application/json

{
  "name": "Teclado",
  "quantity": 15
}
