### Teste da API - Verificar se está online
GET http://localhost:4000/api/teste

###

### Buscar todos os produtos
POST  http://localhost:4000/api/register
Content-Type: application/json

{
  "nome": "Marcelo",
  "email": "mpedrosa.melo@gmail.com",
  "senha": "123456",
  "dataNascimento": "1990-01-01",
  "genero": "Masculino"

}

###

### Cadastrar um novo produto
POST http://localhost:4000/api/products
Content-Type: application/json

{
  "name": "Teclado",
  "quantity": 15
}
